"""
JAMUNIYA-SHAKTAWAT RESIDENCE - MULTI-SHEET DRAWING SET
Plot: 40' E-W x 42' N-S
Generated by TraeCAD Engine v0.1.0

SHEETS INCLUDED:
  Sheet 01: Ground Floor Plan (with 12' Guest Bed Rooms & Clockwise Stairs)
  Sheet 02: First Floor Plan (with 14'x16' Bedroom-3, 7' Mandir/Store)

Orientation: North = Bottom (Main Entry), South = Top (Garh)
             East = Left, West = Right
"""
import sys
import math
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent / "scripts"))
from traecad_engine import *
import fitz

# ======================================================================
# PROJECT CONFIG
# ======================================================================
out_dir = _HERE
(out_dir / 'CAD').mkdir(parents=True, exist_ok=True)
(out_dir / 'PDF').mkdir(parents=True, exist_ok=True)

config = ProjectConfig(
    project_title="JAMUNIYA-SHAKTAWAT RESIDENCE",
    client="SHAKTAWAT FAMILY, JAMUNIYA",
    date="26 AUG 2026",
    drawn_by="TRAE AI ARCHITECTURE STUDIO",
    code_ref="NBC 2016 + IS 3861 + VASTU SHASTRA",
    doc_ref="JSR-REVISED-v3.0",
    base_dir=str(out_dir),
    dxf_subdir="CAD",
    pdf_subdir="PDF",
    paper_size="A4",
    margin_mm=20.0,
)

SW = 110.0 * FT
SH = SW * (config.printable_h_mm / config.printable_w_mm)

# ======================================================================
# DRAWING CONSTANTS
# ======================================================================
PW = 40.0 * FT   # 480"
PH = 42.0 * FT   # 504"
OWT = 12         # Outer wall: 12"
IWT = 8          # Inner wall: 8"

# Center plan in sheet
plan_ox = 22.0 * FT
plan_oy = 15.0 * FT

def X(x): return plan_ox + x
def Y(y): return plan_oy + y

# Interior corners
IX1 = OWT
IX2 = PW - OWT
IY1 = OWT
IY2 = PH - OWT

# West column (Stairs + Bedrooms 2 & 3)
X_WC     = IX2 - 14 * FT
X_WC_IW  = X_WC - IWT
X_STR    = IX2 - 5 * FT

# ======================================================================
# LOCAL HELPER: DOOR SWING (ASCII COMPLIANT)
# ======================================================================
def door_swing(msp, hinge_x, hinge_y, width, swing_dir=1,
               angle=90.0, layer="A-DOOR", lw=18):
    """Draw door leaf + swing arc in plan view."""
    rad = math.radians(angle)
    leaf_ex = hinge_x + width * math.cos(0)
    leaf_ey = hinge_y + width * swing_dir * math.sin(0)
    msp.add_line((hinge_x, hinge_y), (leaf_ex, leaf_ey),
                 dxfattribs={"layer": layer, "lineweight": lw})
    start_a = 0.0 if swing_dir > 0 else 360.0 - angle
    end_a = angle if swing_dir > 0 else 360.0
    msp.add_arc(center=(hinge_x, hinge_y), radius=width,
                start_angle=start_a, end_angle=end_a,
                dxfattribs={"layer": layer, "lineweight": lw})

# ======================================================================
# STAIRS GENERATOR (CLOCKWISE / RIGHT-HAND)
# ======================================================================
def draw_clockwise_stairs(msp, y_sz):
    """Draw clockwise staircase at the top-right (South-West corner)."""
    rect(msp, X(X_STR), Y(y_sz), X(IX2), Y(IY2), layer="A-WALL", lw=30)
    stair_box_w = IX2 - X_STR
    
    # First flight: going North to South (upwards in plan)
    for i in range(8):
        ty = y_sz + (i + 1) * 1.0 * FT
        msp.add_line((X(X_STR), Y(ty)), (X(IX2), Y(ty)),
                     dxfattribs={"layer": "A-WALL", "lineweight": 13})
                     
    # Landing
    rect(msp, X(X_STR), Y(IY2 - 4*FT), X(IX2), Y(IY2 - 0.3*FT), layer="A-FURN", lw=20)
    text_msp(msp, "LANDING", X(X_STR + 2.5*FT), Y(IY2 - 2*FT), h=0.8*FT, layer="A-FURN")
    
    # Second flight: turning West (RIGHT turn)
    for i in range(5):
        tx = X_STR + (i + 0.5) * FT
        msp.add_line((X(tx), Y(y_sz + 0.5*FT)), (X(tx), Y(y_sz + 4*FT)),
                     dxfattribs={"layer": "A-WALL", "lineweight": 13})
                     
    # Up arrow (Clockwise direction)
    msp.add_line((X(X_STR + 0.8*FT), Y(y_sz + 5.5*FT)), (X(X_STR + 4.2*FT), Y(y_sz + 5.5*FT)),
                 dxfattribs={"layer": "A-TEXT-TTL", "lineweight": 25})
    msp.add_line((X(X_STR + 4.2*FT), Y(y_sz + 5.5*FT)), (X(X_STR + 3.2*FT), Y(y_sz + 6.0*FT)),
                 dxfattribs={"layer": "A-TEXT-TTL", "lineweight": 25})
    msp.add_line((X(X_STR + 4.2*FT), Y(y_sz + 5.5*FT)), (X(X_STR + 3.2*FT), Y(y_sz + 5.0*FT)),
                 dxfattribs={"layer": "A-TEXT-TTL", "lineweight": 25})
    
    text_msp(msp, "STAIRS\n5' WIDE\nCLOCKWISE", X(X_STR + 2.5*FT), Y(y_sz + 9*FT),
             h=1.0*FT, layer="A-TEXT-TTL")

# ======================================================================
# SHEET 01: GROUND FLOOR PLAN
# ======================================================================
def draw_ground_floor():
    doc, msp = setup_doc(sheet_w=SW, sheet_h=SH, config=config)
    
    # 1. Outer Boundary & Direction Indicators
    rect(msp, X(0), Y(0), X(PW), Y(PH), layer="A-WALL", lw=50)
    
    text_msp(msp, "NORTH - UTTAR (MAIN ENTRY)", X(PW/2), Y(-3*FT), h=1.8*FT, layer="A-TEXT-TTL")
    text_msp(msp, "SOUTH - DAKSHINA (GARH SIDE)", X(PW/2), Y(PH + 1.5*FT), h=1.8*FT, layer="A-TEXT-TTL")
    text_msp(msp, "EAST - PURVA", X(-4*FT), Y(PH/2), h=1.5*FT, layer="A-TEXT-TTL", rot=90.0)
    text_msp(msp, "WEST - PASHCHIM", X(PW + 3*FT), Y(PH/2), h=1.5*FT, layer="A-TEXT-TTL", rot=90.0)
    
    # Primitives & dimensions
    arch_dim_h(msp, X(0), Y(PH + 3*FT), X(PW), "40'-0\" (PLOT WIDTH E-W)", offset=0.9*FT, text_h=0.9*FT)
    arch_dim_v(msp, X(-3.5*FT), Y(0), Y(PH), "42'-0\" (PLOT DEPTH N-S)", offset=-1.5*FT, text_h=0.9*FT)
    
    # 2. X Division: Left Column is 12' Guest Bed Rooms (internally 144")
    X_LC = IX1 + 12 * FT     # = 12 + 144 = 156"
    X_LC_IW = X_LC + IWT     # = 164"
    
    # Draw left column partition wall
    rect(msp, X(X_LC), Y(IY1), X(X_LC_IW), Y(IY2), layer="A-WALL", lw=35)
    
    # Y Division in Left Column (South to North)
    # Total available interior: 480"
    # Pooja (11' = 132") | Wall (8") | Guest-1 (11' = 132") | Wall (8") | Baths (5' = 60") | Wall (8") | Guest-2 (11' = 132")
    Y_PJ_B = IY2 - 11*FT        # = 492 - 132 = 360"
    Y_PJ_IW = Y_PJ_B - IWT      # = 352"
    
    Y_G1_B = Y_PJ_IW - 11*FT    # = 352 - 132 = 220"
    Y_G1_IW = Y_G1_B - IWT      # = 212"
    
    Y_BT_B = Y_G1_IW - 5*FT     # = 212 - 60 = 152"
    Y_BT_IW = Y_BT_B - IWT      # = 144"
    
    # Draw the Y-axis partition walls in Left Column
    rect(msp, X(IX1), Y(Y_PJ_B), X(X_LC), Y(Y_PJ_IW), layer="A-WALL", lw=30)
    rect(msp, X(IX1), Y(Y_G1_B), X(X_LC), Y(Y_G1_IW), layer="A-WALL", lw=30)
    rect(msp, X(IX1), Y(Y_BT_B), X(X_LC), Y(Y_BT_IW), layer="A-WALL", lw=30)
    
    # ---- POOJA ROOM (12' x 11') ----
    pj_cx = (IX1 + X_LC) / 2
    # Altar on South wall
    rect(msp, X(IX1 + 1*FT), Y(IY2 - 2.5*FT), X(X_LC - 1*FT), Y(IY2 - 0.8*FT), layer="A-FURN", lw=20)
    text_msp(msp, "ALTAR", X(pj_cx), Y(IY2 - 1.6*FT), h=0.6*FT, layer="A-FURN")
    text_msp(msp, "POOJA ROOM\n12' x 11'", X(pj_cx), Y((Y_PJ_B + IY2)/2), h=1.2*FT, layer="A-TEXT-TTL")
    door_swing(msp, X(X_LC), Y(Y_PJ_B + 1*FT), width=3.0*FT, swing_dir=1, layer="A-DOOR")
    
    # ---- GUEST ROOM-1 (12' x 11') ----
    g1_cx = (IX1 + X_LC) / 2
    # Bed: headboard South
    rect(msp, X(g1_cx - 3.5*FT), Y(Y_PJ_IW - 6.5*FT), X(g1_cx + 3.5*FT), Y(Y_PJ_IW - 0.8*FT), layer="A-FURN", lw=20)
    msp.add_line((X(g1_cx - 3.5*FT), Y(Y_PJ_IW - 0.8*FT)), (X(g1_cx + 3.5*FT), Y(Y_PJ_IW - 0.8*FT)),
                 dxfattribs={"layer": "A-FURN", "lineweight": 50})
    text_msp(msp, "BED (HEAD=SOUTH)", X(g1_cx), Y(Y_PJ_IW - 3.8*FT), h=0.7*FT, layer="A-FURN")
    # Wardrobe: North wall
    rect(msp, X(IX1 + 1*FT), Y(Y_G1_B + 0.3*FT), X(X_LC - 1*FT), Y(Y_G1_B + 1.8*FT), layer="A-FURN", lw=18)
    text_msp(msp, "WARDROBE - NORTH WALL", X(g1_cx), Y(Y_G1_B + 1.0*FT), h=0.7*FT, layer="A-FURN")
    
    text_msp(msp, "GUEST ROOM-1\n12' x 11'", X(g1_cx), Y(Y_G1_B + 4.2*FT), h=1.2*FT, layer="A-TEXT-TTL")
    door_swing(msp, X(X_LC), Y(Y_G1_B + 1*FT), width=3.0*FT, swing_dir=1, layer="A-DOOR")
    
    # ---- ATTACHED BATHROOMS (Two of 5.6' x 5' each, split vertically) ----
    X_BT_MID = (IX1 + X_LC) / 2
    # Split wall
    rect(msp, X(X_BT_MID - IWT/2), Y(Y_BT_B), X(X_BT_MID + IWT/2), Y(Y_G1_IW), layer="A-WALL", lw=20)
    # Bath-1 (Left - attached to Guest 1)
    circle(msp, X(IX1 + 1.5*FT), Y(Y_BT_B + 1.5*FT), 0.7*FT, layer="A-FURN", lw=13)
    text_msp(msp, "BATH-1\n5.6'x5'", X((IX1 + X_BT_MID)/2), Y((Y_BT_B + Y_G1_IW)/2), h=0.8*FT, layer="A-TEXT-TTL")
    door_swing(msp, X(IX1 + 1.5*FT), Y(Y_G1_IW), width=2.5*FT, swing_dir=-1, layer="A-DOOR") # opens from Guest 1
    
    # Bath-2 (Right - attached to Guest 2)
    circle(msp, X(X_LC - 1.5*FT), Y(Y_BT_B + 1.5*FT), 0.7*FT, layer="A-FURN", lw=13)
    text_msp(msp, "BATH-2\n5.6'x5'", X((X_BT_MID + X_LC)/2), Y((Y_BT_B + Y_G1_IW)/2), h=0.8*FT, layer="A-TEXT-TTL")
    door_swing(msp, X(X_LC - 1.5*FT), Y(Y_BT_B), width=2.5*FT, swing_dir=1, layer="A-DOOR") # opens from Guest 2
    
    # ---- GUEST ROOM-2 (12' x 11') ----
    g2_cx = (IX1 + X_LC) / 2
    # Bed: headboard South
    rect(msp, X(g2_cx - 3.5*FT), Y(Y_BT_IW - 6.5*FT), X(g2_cx + 3.5*FT), Y(Y_BT_IW - 0.8*FT), layer="A-FURN", lw=20)
    msp.add_line((X(g2_cx - 3.5*FT), Y(Y_BT_IW - 0.8*FT)), (X(g2_cx + 3.5*FT), Y(Y_BT_IW - 0.8*FT)),
                 dxfattribs={"layer": "A-FURN", "lineweight": 50})
    text_msp(msp, "BED (HEAD=SOUTH)", X(g2_cx), Y(Y_BT_IW - 3.8*FT), h=0.7*FT, layer="A-FURN")
    # Wardrobe: North wall
    rect(msp, X(IX1 + 1*FT), Y(IY1 + 0.3*FT), X(X_LC - 1*FT), Y(IY1 + 1.8*FT), layer="A-FURN", lw=18)
    text_msp(msp, "WARDROBE - NORTH WALL", X(g2_cx), Y(IY1 + 1.0*FT), h=0.7*FT, layer="A-FURN")
    
    text_msp(msp, "GUEST ROOM-2\n12' x 11'", X(g2_cx), Y(IY1 + 4.2*FT), h=1.2*FT, layer="A-TEXT-TTL")
    door_swing(msp, X(X_LC), Y(IY1 + 1*FT), width=3.0*FT, swing_dir=1, layer="A-DOOR")
    
    # 3. Right Side: MASSIVE L-SHAPED HALL
    # Stairs footprint (aligns with 1st floor)
    # South zone starts at Y = PH - OWT - 13.5*FT = 330"
    Y_SZ_GF = IY2 - 13.5 * FT
    draw_clockwise_stairs(msp, Y_SZ_GF)
    
    # Hall Main Space (25'-4" wide, 40' deep total)
    hall_cx = (X_LC_IW + IX2) / 2
    text_msp(msp, "MASSIVE HALL\n25.3' x 40.0'", X(hall_cx), Y(PH * 0.4), h=1.4*FT, layer="A-TEXT-TTL")
    
    # Main Entrance door (bottom/North wall)
    door_swing(msp, X(hall_cx - 3.0*FT), Y(IY1), width=6.0*FT, swing_dir=1, layer="A-DOOR")
    text_msp(msp, "6' WIDE MAIN DOUBLE DOOR", X(hall_cx), Y(IY1 + 6.5*FT), h=0.8*FT, layer="A-DOOR")
    
    # Sofa set in Hall
    rect(msp, X(X_LC_IW + 2*FT), Y(Y_SZ_GF + 1*FT), X(X_LC_IW + 14*FT), Y(Y_SZ_GF + 3.2*FT), layer="A-FURN", lw=13)
    rect(msp, X(X_LC_IW + 2*FT), Y(Y_SZ_GF + 3.2*FT), X(X_LC_IW + 4*FT), Y(Y_SZ_GF + 6*FT), layer="A-FURN", lw=13)
    text_msp(msp, "L-SOFA SET", X(X_LC_IW + 8*FT), Y(Y_SZ_GF + 2.1*FT), h=0.7*FT, layer="A-FURN")
    
    # 4. Sheet Details
    draw_sheet_frame_and_titleblock(
        msp, SW, SH,
        sheet_no="SHEET 01 OF 02",
        sheet_title="GROUND FLOOR PLAN - JAMUNIYA-SHAKTAWAT RESIDENCE",
        scale_txt='1/4" = 1\'-0"',
        config=config,
        notes=[
            "Plot Size: 40' x 42' (42' = North-South). Outer Wall: 12\", Inner Wall: 8\".",
            "Left Column: Guest Bed Rooms upgraded to 12' wide (internally 144\").",
            "Attached Bathrooms (5.6' x 5' each) with independent entry for guests.",
            "Staircase turn Clockwise (Right-hand) to align with First Floor.",
            "Pooja Room (12' x 11') placed in East-South (Vastu-preferred).",
            "RCC structure designed for Zone III Seismic compliance (IS 1893:2016).",
        ]
    )
    
    # Save DXF
    dxf_path = out_dir / 'CAD' / 'JSR-Ground-Floor-Plan.dxf'
    doc.saveas(str(dxf_path))
    print(f"[OK] Ground Floor DXF saved: {dxf_path.name}")
    pdf_out = export_dxf_to_pdf(dxf_path, config)
    print(f"[OK] Ground Floor PDF saved: {pdf_out}")
    return pdf_out

# ======================================================================
# SHEET 02: FIRST FLOOR PLAN
# ======================================================================
def draw_first_floor():
    doc, msp = setup_doc(sheet_w=SW, sheet_h=SH, config=config)
    
    # 1. Outer Boundary & Directions
    rect(msp, X(0), Y(0), X(PW), Y(PH), layer="A-WALL", lw=50)
    
    text_msp(msp, "NORTH - UTTAR (MAIN ENTRY)", X(PW/2), Y(-3*FT), h=1.8*FT, layer="A-TEXT-TTL")
    text_msp(msp, "SOUTH - DAKSHINA (GARH SIDE)", X(PW/2), Y(PH + 1.5*FT), h=1.8*FT, layer="A-TEXT-TTL")
    text_msp(msp, "EAST - PURVA", X(-4*FT), Y(PH/2), h=1.5*FT, layer="A-TEXT-TTL", rot=90.0)
    text_msp(msp, "WEST - PASHCHIM", X(PW + 3*FT), Y(PH/2), h=1.5*FT, layer="A-TEXT-TTL", rot=90.0)
    
    # Outer dimensions
    arch_dim_h(msp, X(0), Y(PH + 3*FT), X(PW), "40'-0\" (PLOT WIDTH E-W)", offset=0.9*FT, text_h=0.9*FT)
    arch_dim_v(msp, X(-3.5*FT), Y(0), Y(PH), "42'-0\" (PLOT DEPTH N-S)", offset=-1.5*FT, text_h=0.9*FT)
    
    # divisions
    X_EC  = IX1 + 14 * FT + IWT
    X_EC_IW = X_EC + IWT
    
    # South zone
    Y_SZ_FF = IY2 - 13.5 * FT
    Y_SZ_IW  = Y_SZ_FF - IWT
    
    # Middle band
    Y_MB_T   = Y_SZ_IW
    Y_MB_B   = Y_MB_T - 5 * FT
    Y_MB_IW  = Y_MB_B - IWT
    
    # Bedroom-3
    Y_WBR_T  = Y_SZ_IW
    Y_WBR_B  = Y_WBR_T - 16 * FT
    Y_WBR_IW = Y_WBR_B - IWT
    
    # Bedroom-2
    Y_B2_T   = Y_WBR_IW
    Y_B2_B   = IY1
    
    # Bedroom-1
    Y_B1_T   = Y_MB_B
    Y_B1_B   = IY1
    
    # Bathrooms
    BATH_W   = 42
    DUCT_W   = 12
    X_B1_L   = X_EC_IW
    X_B1_R   = X_B1_L + BATH_W
    X_DT_L   = X_B1_R
    X_DT_R   = X_DT_L + DUCT_W
    X_B2_L   = X_DT_R
    X_B2_R   = X_B2_L + BATH_W
    
    WIC_NS   = 6 * FT
    BATH_NS  = 8 * FT
    Y_WIC_B  = IY1
    Y_WIC_T  = IY1 + WIC_NS
    Y_BAT_B  = Y_WIC_T + IWT
    Y_BAT_T  = Y_BAT_B + BATH_NS
    
    # ---- 2. SOUTH ZONE: Kitchen + Living + Stairs ----
    rect(msp, X(IX1), Y(Y_SZ_FF), X(X_EC), Y(IY2), layer="A-WALL", lw=35)
    # Counter
    rect(msp, X(IX1+0.5*FT), Y(IY2-2.8*FT), X(X_EC-0.5*FT), Y(IY2-0.7*FT), layer="A-FURN", lw=13)
    text_msp(msp, "SLAB + SINK", X(IX1+7*FT), Y(IY2-1.8*FT), h=0.6*FT, layer="A-FURN")
    rect(msp, X(IX1+0.5*FT), Y(IY2-4.8*FT), X(IX1+3.5*FT), Y(IY2-2.8*FT), layer="A-FURN", lw=13)
    text_msp(msp, "STOVE", X(IX1+2*FT), Y(IY2-3.8*FT), h=0.6*FT, layer="A-FURN")
    rect(msp, X(X_EC-2*FT), Y(IY2-4.5*FT), X(X_EC-0.5*FT), Y(IY2-2.8*FT), layer="A-FURN", lw=13)
    text_msp(msp, "REF", X(X_EC-1.25*FT), Y(IY2-3.7*FT), h=0.5*FT, layer="A-FURN")
    # Dining
    rect(msp, X(IX1+1*FT), Y(Y_SZ_FF+1.5*FT), X(IX1+9*FT), Y(Y_SZ_FF+5.5*FT), layer="A-FURN", lw=13)
    text_msp(msp, "DINING\n4'x6'", X(IX1+5*FT), Y(Y_SZ_FF+3.5*FT), h=0.7*FT, layer="A-FURN")
    text_msp(msp, "KITCHEN &\nDINING\n14' x 15'", X(IX1+7*FT), Y(Y_SZ_FF+9*FT), h=1.2*FT, layer="A-TEXT-TTL")
    door_swing(msp, X(X_EC), Y(Y_SZ_FF + 5*FT), width=3*FT, swing_dir=1, layer="A-DOOR")
    
    # Wall: Kitchen | Living
    rect(msp, X(X_EC), Y(Y_SZ_FF), X(X_EC_IW), Y(IY2), layer="A-WALL", lw=35)
    
    # Living area
    rect(msp, X(X_EC_IW), Y(Y_SZ_FF), X(X_STR - IWT), Y(IY2), layer="A-WALL", lw=30)
    # L-sofa
    rect(msp, X(X_EC_IW+2*FT), Y(IY2-5.5*FT), X(X_EC_IW+13*FT), Y(IY2-3.5*FT), layer="A-FURN", lw=13)
    rect(msp, X(X_EC_IW+2*FT), Y(IY2-3.5*FT), X(X_EC_IW+3.8*FT), Y(IY2-1.2*FT), layer="A-FURN", lw=13)
    rect(msp, X(X_EC_IW+11.2*FT), Y(IY2-3.5*FT), X(X_EC_IW+13*FT), Y(IY2-1.2*FT), layer="A-FURN", lw=13)
    text_msp(msp, "SOFA SET", X(X_EC_IW+7.5*FT), Y(IY2-4.5*FT), h=0.7*FT, layer="A-FURN")
    rect(msp, X(X_EC_IW+4.5*FT), Y(IY2-3.2*FT), X(X_EC_IW+9.5*FT), Y(IY2-1.5*FT), layer="A-FURN", lw=13)
    text_msp(msp, "LIVING AREA\n22' x 15'", X((X_EC_IW + X_STR)/2), Y(Y_SZ_FF + 5*FT), h=1.2*FT, layer="A-TEXT-TTL")
    
    # Wall: Living | Stairs
    rect(msp, X(X_STR-IWT), Y(Y_SZ_FF), X(X_STR), Y(IY2), layer="A-WALL", lw=35)
    
    # Stairs (identical clockwise turn)
    draw_clockwise_stairs(msp, Y_SZ_FF)
    
    # ---- 3. MIDDLE BAND ----
    rect(msp, X(IX1), Y(Y_SZ_IW), X(X_WC_IW), Y(Y_SZ_FF), layer="A-WALL", lw=35)
    # Store
    X_ST_R = IX1 + 7 * FT
    rect(msp, X(IX1), Y(Y_MB_B), X(X_ST_R), Y(Y_MB_T), layer="A-WALL", lw=30)
    door_swing(msp, X(IX1+1*FT), Y(Y_MB_B), width=2.5*FT, swing_dir=-1, layer="A-DOOR")
    text_msp(msp, "STORE\n7'x5'", X(IX1 + 3.5*FT), Y((Y_MB_B+Y_MB_T)/2), h=1.0*FT, layer="A-TEXT-TTL")
    # Store | Mandir wall
    rect(msp, X(X_ST_R), Y(Y_MB_B), X(X_ST_R+IWT), Y(Y_MB_T), layer="A-WALL", lw=30)
    
    # Mandir
    X_MD_L = X_ST_R + IWT
    X_MD_R = X_EC
    mandir_cx = (X_MD_L + X_MD_R) / 2
    rect(msp, X(X_MD_L), Y(Y_MB_B), X(X_MD_R), Y(Y_MB_T), layer="A-WALL", lw=30)
    door_swing(msp, X(mandir_cx - 1.5*FT), Y(Y_MB_B), width=2.5*FT, swing_dir=1, layer="A-DOOR") # opens from corridor
    rect(msp, X(X_MD_L+0.4*FT), Y(Y_MB_T-2.2*FT), X(X_MD_R-0.4*FT), Y(Y_MB_T-0.7*FT), layer="A-FURN", lw=20)
    text_msp(msp, "ALTAR", X(mandir_cx), Y(Y_MB_T-1.5*FT), h=0.6*FT, layer="A-FURN")
    text_msp(msp, "MANDIR\n7'x5'\n(DOOR FROM\nCORRIDOR - R7)", X(mandir_cx), Y(Y_MB_B + 1*FT), h=0.8*FT, layer="A-TEXT-TTL")
    
    # Wall: East column
    rect(msp, X(X_EC), Y(IY1), X(X_EC_IW), Y(Y_MB_B), layer="A-WALL", lw=35)
    
    # Bathroom upper
    BATH_UPR_W = 8 * FT
    BATH_UPR_L = X_EC_IW
    BATH_UPR_R = X_EC_IW + BATH_UPR_W
    rect(msp, X(BATH_UPR_L), Y(Y_MB_B), X(BATH_UPR_R), Y(Y_MB_T), layer="A-WALL", lw=25)
    circle(msp, X(BATH_UPR_R-1.5*FT), Y(Y_MB_B+1.5*FT), 0.7*FT, layer="A-FURN", lw=13)
    rect(msp, X(BATH_UPR_L+0.4*FT), Y(Y_MB_T-2.2*FT), X(BATH_UPR_L+2.8*FT), Y(Y_MB_T-0.6*FT), layer="A-FURN", lw=13)
    text_msp(msp, "BATHROOM\n8' x 5'", X((BATH_UPR_L+BATH_UPR_R)/2), Y((Y_MB_B+Y_MB_T)/2), h=1.0*FT, layer="A-TEXT-TTL")
    
    if BATH_UPR_R < X_WC:
        text_msp(msp, "CORRIDOR (4')", X((BATH_UPR_R+X_WC)/2), Y((Y_MB_B+Y_MB_T)/2), h=0.8*FT, layer="A-TEXT-TTL")
        
    rect(msp, X(X_WC_IW), Y(IY1), X(X_WC), Y(Y_MB_T), layer="A-WALL", lw=35)
    
    # ---- 4. BEDROOM-3 (WEST - 14' x 16') ----
    rect(msp, X(X_WC), Y(Y_WBR_B), X(IX2), Y(Y_WBR_T), layer="A-WALL", lw=35)
    door_swing(msp, X(X_WC), Y(Y_MB_B - 3*FT), width=3*FT, swing_dir=-1, layer="A-DOOR")
    wbr_cx = (X_WC + IX2) / 2
    # Bed: headboard South
    rect(msp, X(wbr_cx-3.5*FT), Y(Y_WBR_T-8*FT), X(wbr_cx+3.5*FT), Y(Y_WBR_T-0.8*FT), layer="A-FURN", lw=20)
    msp.add_line((X(wbr_cx-3.5*FT), Y(Y_WBR_T-0.8*FT)), (X(wbr_cx+3.5*FT), Y(Y_WBR_T-0.8*FT)),
                 dxfattribs={"layer": "A-FURN", "lineweight": 50})
    text_msp(msp, "KING BED\n(HEAD = SOUTH)\nVASTU - R8", X(wbr_cx), Y(Y_WBR_T-5*FT), h=0.8*FT, layer="A-FURN")
    # Wardrobe: North wall
    rect(msp, X(X_WC+1*FT), Y(Y_WBR_B+0.4*FT), X(IX2-1*FT), Y(Y_WBR_B+2.2*FT), layer="A-FURN", lw=20)
    text_msp(msp, "WARDROBE - NORTH WALL (R-8)", X(wbr_cx), Y(Y_WBR_B+1.3*FT), h=0.7*FT, layer="A-FURN")
    
    text_msp(msp, "BEDROOM-3\n14' x 16'\n(WEST - UPDATED)", X(wbr_cx), Y(Y_WBR_B + 6*FT), h=1.2*FT, layer="A-TEXT-TTL")
    arch_dim_h(msp, X(X_WC), Y(Y_WBR_B-2*FT), X(IX2), "14'-0\"", offset=-1.2*FT, text_h=0.8*FT)
    arch_dim_v(msp, X(IX2+2*FT), Y(Y_WBR_B), Y(Y_WBR_T), "16'-0\"", offset=0.8*FT, text_h=0.8*FT)
    
    # ---- 5. BEDROOM-2 (WEST - 14' x 9'-2") ----
    rect(msp, X(X_WC), Y(Y_B2_B), X(IX2), Y(Y_B2_T), layer="A-WALL", lw=35)
    door_swing(msp, X(X_WC), Y(IY1+4*FT), width=3*FT, swing_dir=-1, layer="A-DOOR")
    b2_cx = (X_WC + IX2) / 2
    b2_depth = Y_B2_T - Y_B2_B
    b2_depth_ft = b2_depth / FT
    
    # Bed: headboard South
    rect(msp, X(b2_cx-3*FT), Y(Y_B2_T-6.2*FT), X(b2_cx+3*FT), Y(Y_B2_T-0.8*FT), layer="A-FURN", lw=20)
    msp.add_line((X(b2_cx-3*FT), Y(Y_B2_T-0.8*FT)), (X(b2_cx+3*FT), Y(Y_B2_T-0.8*FT)),
                 dxfattribs={"layer": "A-FURN", "lineweight": 50})
    text_msp(msp, "BED\n(HEAD=SOUTH)", X(b2_cx), Y(Y_B2_T-3.8*FT), h=0.7*FT, layer="A-FURN")
    # Wardrobe: North wall
    rect(msp, X(X_WC+1*FT), Y(Y_B2_B+0.3*FT), X(IX2-1*FT), Y(Y_B2_B+1.8*FT), layer="A-FURN", lw=18)
    text_msp(msp, "WARDROBE - NORTH WALL", X(b2_cx), Y(Y_B2_B+1.0*FT), h=0.7*FT, layer="A-FURN")
    
    text_msp(msp, f"BEDROOM-2\n14' x {b2_depth_ft:.1f}'\n[WEST SIDE]", X(b2_cx), Y(Y_B2_B + 4.2*FT), h=1.1*FT, layer="A-TEXT-TTL")
    arch_dim_v(msp, X(IX2+2*FT), Y(Y_B2_B), Y(Y_B2_T), f"{b2_depth_ft:.1f}' BED-2", offset=0.8*FT, text_h=0.8*FT)
    
    # ---- 6. BEDROOM-1 (EAST - 14'-8" x 19'-4") ----
    rect(msp, X(IX1), Y(Y_B1_B), X(X_EC), Y(Y_B1_T), layer="A-WALL", lw=35)
    door_swing(msp, X(X_EC), Y(IY1+4*FT), width=3*FT, swing_dir=1, layer="A-DOOR")
    b1_cx = (IX1 + X_EC) / 2
    b1_depth = Y_B1_T - Y_B1_B
    b1_depth_ft = b1_depth / FT
    # Bed: headboard South
    rect(msp, X(b1_cx-3.5*FT), Y(Y_B1_T-8.5*FT), X(b1_cx+3.5*FT), Y(Y_B1_T-0.8*FT), layer="A-FURN", lw=20)
    msp.add_line((X(b1_cx-3.5*FT), Y(Y_B1_T-0.8*FT)), (X(b1_cx+3.5*FT), Y(Y_B1_T-0.8*FT)),
                 dxfattribs={"layer": "A-FURN", "lineweight": 50})
    text_msp(msp, "KING BED\n(HEAD=SOUTH)", X(b1_cx), Y(Y_B1_T-5.5*FT), h=0.7*FT, layer="A-FURN")
    # Wardrobe: North wall
    rect(msp, X(IX1+0.8*FT), Y(IY1+0.4*FT), X(X_EC-0.8*FT), Y(IY1+2.2*FT), layer="A-FURN", lw=18)
    text_msp(msp, "WARDROBE - NORTH WALL", X(b1_cx), Y(IY1+1.3*FT), h=0.7*FT, layer="A-FURN")
    
    text_msp(msp, f"BEDROOM-1\n14' x {b1_depth_ft:.1f}'\n[MASTER, EAST]", X(b1_cx), Y(IY1+5*FT), h=1.2*FT, layer="A-TEXT-TTL")
    
    # ---- 7. BATHROOMS + OPEN DUCT SHAFT ----
    rect(msp, X(X_EC_IW), Y(Y_BAT_T), X(X_WC_IW), Y(Y_MB_B), layer="A-WALL", lw=20)
    # Bath-1
    rect(msp, X(X_B1_L), Y(Y_BAT_B), X(X_B1_R), Y(Y_BAT_T), layer="A-WALL", lw=25)
    circle(msp, X(X_B1_L+2*FT), Y(Y_BAT_B+1.5*FT), 0.7*FT, layer="A-FURN", lw=13)
    rect(msp, X(X_B1_L+0.3*FT), Y(Y_BAT_T-2.2*FT), X(X_B1_R-0.3*FT), Y(Y_BAT_T-0.5*FT), layer="A-FURN", lw=13)
    door_swing(msp, X(X_B1_L), Y(Y_BAT_B), width=2.5*FT, swing_dir=-1, layer="A-DOOR")
    text_msp(msp, "BATH-1\n3.5'x8'", X((X_B1_L+X_B1_R)/2), Y((Y_BAT_B+Y_BAT_T)/2), h=0.8*FT, layer="A-TEXT-TTL")
    
    # Open Duct Shaft
    rect(msp, X(X_DT_L), Y(IY1), X(X_DT_R), Y(Y_MB_B), layer="A-JALI", lw=20)
    msp.add_line((X(X_DT_L), Y(IY1)), (X(X_DT_R), Y(Y_MB_B)), dxfattribs={"layer": "A-HATCH", "lineweight": 13})
    msp.add_line((X(X_DT_R), Y(IY1)), (X(X_DT_L), Y(Y_MB_B)), dxfattribs={"layer": "A-HATCH", "lineweight": 13})
    text_msp(msp, "OPEN\nDUCT\nSHAFT\n(R-6)", X((X_DT_L+X_DT_R)/2), Y((IY1+Y_BAT_T)/2), h=0.7*FT, layer="A-TEXT-TTL")
    
    # Bath-2
    rect(msp, X(X_B2_L), Y(Y_BAT_B), X(X_B2_R), Y(Y_BAT_T), layer="A-WALL", lw=25)
    circle(msp, X(X_B2_L+2*FT), Y(Y_BAT_B+1.5*FT), 0.7*FT, layer="A-FURN", lw=13)
    rect(msp, X(X_B2_L+0.3*FT), Y(Y_BAT_T-2.2*FT), X(X_B2_R-0.3*FT), Y(Y_BAT_T-0.5*FT), layer="A-FURN", lw=13)
    door_swing(msp, X(X_B2_R), Y(Y_BAT_B), width=2.5*FT, swing_dir=1, layer="A-DOOR")
    text_msp(msp, "BATH-2\n3.5'x8'", X((X_B2_L+X_B2_R)/2), Y((Y_BAT_B+Y_BAT_T)/2), h=0.8*FT, layer="A-TEXT-TTL")
    
    # WIC-1
    rect(msp, X(X_B1_L), Y(Y_WIC_B), X(X_B1_R), Y(Y_WIC_T), layer="A-WALL", lw=20)
    text_msp(msp, "WIC-1\n3.5'x6'", X((X_B1_L+X_B1_R)/2), Y((Y_WIC_B+Y_WIC_T)/2), h=0.7*FT, layer="A-TEXT-TTL")
    # WIC-2
    rect(msp, X(X_B2_L), Y(Y_WIC_B), X(X_B2_R), Y(Y_WIC_T), layer="A-WALL", lw=20)
    text_msp(msp, "WIC-2\n3.5'x6'", X((X_B2_L+X_B2_R)/2), Y((Y_WIC_B+Y_WIC_T)/2), h=0.7*FT, layer="A-TEXT-TTL")
    
    # South zone dimensions
    arch_dim_v(msp, X(IX2+2*FT), Y(Y_SZ_FF), Y(IY2), "13'-6\" SOUTH ZONE", offset=0.8*FT, text_h=0.8*FT)
    draw_north_arrow(msp, X(PW + 10*FT), Y(PH * 0.5), size=5*FT)
    
    # Room Schedule
    tbl_x = X(PW + 6*FT)
    tbl_y = Y(PH * 0.75)
    text_msp(msp, "ROOM SCHEDULE", tbl_x, tbl_y, h=1.2*FT, layer="A-TEXT-TTL", align=TextEntityAlignment.LEFT)
    schedule = [
        ("BEDROOM-1 (Master/East)",    f"14' x {b1_depth_ft:.0f}'"),
        ("BEDROOM-2 (West/Lower)",     f"14' x {b2_depth_ft:.1f}'"),
        ("BEDROOM-3 (West/Upper)",     "14' x 16'"),
        ("KITCHEN & DINING",           "14' x 15'"),
        ("LIVING AREA",                "22' x 15'"),
        ("STAIRS",                     "5' wide, Clockwise"),
        ("MANDIR",                     "7' x 5'"),
        ("STORE",                      "7' x 5'"),
        ("BATHROOM (Upper)",           "8' x 5'"),
        ("BATH-1 + BATH-2 (Lower)",    "3.5' x 8' each"),
        ("WALK-IN CLOSET x2",          "3.5' x 6' each"),
        ("OPEN DUCT SHAFT",            "1' x full height"),
        ("OUTER WALL",                 "12\" thick"),
        ("INNER WALL",                 "8\" thick"),
        ("PLOT SIZE",                  "40' x 42'"),
    ]
    for i, (room, dim) in enumerate(schedule):
        text_msp(msp, f"{room}:", tbl_x, tbl_y - (i+1)*0.75*FT, h=0.7*FT, layer="A-TEXT-TTL", align=TextEntityAlignment.LEFT)
        text_msp(msp, dim, tbl_x + 20*FT, tbl_y - (i+1)*0.75*FT, h=0.7*FT, layer="A-TEXT", align=TextEntityAlignment.LEFT)
        
    # Title Block
    draw_sheet_frame_and_titleblock(
        msp, SW, SH,
        sheet_no="SHEET 02 OF 02",
        sheet_title="FIRST FLOOR PLAN - JAMUNIYA-SHAKTAWAT RESIDENCE",
        scale_txt='1/4" = 1\'-0"',
        config=config,
        notes=[
            "Plot Size: 40' x 42' (42' = North-South). Outer Wall: 12\", Inner Wall: 8\".",
            "Store 7'x5' + Mandir 7'x5' side-by-side in East column.",
            "Bedroom-3 (West) optimized to 14'x16'. Fits king size bed Vastu-style.",
            "Bedroom-2 (West) sized 14'x9'-2\" with North wardrobe to prevent overlaps.",
            "Staircase clockwise (right-hand) turn. Width 5' compliant with NBC 2016.",
            "1' open duct shaft between Bath-1 and Bath-2 for natural ventilation.",
            "All wardrobes on North wall, Bed headboards on South wall (Vastu Shastra).",
        ]
    )
    
    # Save DXF
    dxf_path = out_dir / 'CAD' / 'JSR-First-Floor-Plan.dxf'
    doc.saveas(str(dxf_path))
    print(f"[OK] First Floor DXF saved: {dxf_path.name}")
    pdf_out = export_dxf_to_pdf(dxf_path, config)
    print(f"[OK] First Floor PDF saved: {pdf_out}")
    return pdf_out

# ======================================================================
# COMBINE AND RENDER PREVIEWS
# ======================================================================
def merge_and_preview(pdf1, pdf2):
    combined_path = out_dir / 'PDF' / 'JSR-Revised-Floor-Plans-v3.pdf'
    
    doc_out = fitz.open()
    for p in [pdf1, pdf2]:
        doc_in = fitz.open(p)
        doc_out.insert_pdf(doc_in)
        doc_in.close()
    doc_out.save(str(combined_path))
    doc_out.close()
    print(f"[OK] Combined PDF saved: {combined_path.name}")
    
    # Render PNG previews for review
    preview_dir = Path(r"C:\Users\Rajkumar.DESKTOP-4ISBKM0\.gemini\antigravity-ide\brain\76c87207-4016-414e-95b6-0555bf0e8b3b\scratch\pdf_previews")
    preview_dir.mkdir(parents=True, exist_ok=True)
    
    doc = fitz.open(str(combined_path))
    for i in range(len(doc)):
        page = doc[i]
        pix = page.get_pixmap(dpi=150)
        png_path = preview_dir / f"JSR-Page-{i+1}.png"
        pix.save(str(png_path))
        print(f"[OK] Rendered preview page {i+1} to {png_path.name}")
    doc.close()

if __name__ == '__main__':
    print("============================================================")
    print("JAMUNIYA-SHAKTAWAT - GENERATING BOTH FLOORS v3.0")
    print("============================================================")
    pdf1 = draw_ground_floor()
    pdf2 = draw_first_floor()
    merge_and_preview(pdf1, pdf2)
    print("============================================================")
    print("ALL SHEETS GENERATED, MERGED, AND PREVIEWED SUCCESSFULLY!")
    print("============================================================")
